config/routes.rb
Rails.application.routes.draw do
  root 'links#index'
  resources :links, except: %i[show edit update]
  get '/:short_url', to: 'links#show'
  get 'shortened/:short_url', to: 'links#shortened', as: :shortened
  get 'links/fetch_original_url'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
# frozen_string_literal: true

# :Link Model containing the validations and callbacks:
class Link < ApplicationRecord
  UNIQUE_ID_LENGTH = 6
  validates :original_url, presence: true, on: :create
  validates :original_url, format: URI::regexp(%w[http https])
  before_create :generate_short_url, :sanitize
  
  # GENERATE A UNIQUE URL FOR GIVEN WEB ADDRESS BEFORE SAVING INTO DATABASE
  def generate_short_url
    url = SecureRandom.uuid[0..5]
    old_url = Link.where(short_url: url).last
    if old_url.present?
      self.generate_short_url
    else
      self.short_url = url
    end
  end

  # CHECK IF ANY URL EXIST BEFORE SAVING IT TO DATABASE
  def find_duplicate
    Link.find_by_sanitize_url(self.sanitize_url)
  end

  def new_url?
    find_duplicate.nil?
  end
  
  # SANITIZE THE USER GIVEN URL
  def sanitize
    self.original_url.strip!
    self.sanitize_url = self.original_url.downcase.gsub(/(https?:\/\/)|(www\.)/, "")
    self.sanitize_url = "http://#{self.sanitize_url}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
# frozen_string_literal: true

# :Links Controller for handling Links Actions:
class LinksController < ApplicationController
  before_action :set_link, only: %i[destroy]
  before_action :find_link, only: %i[show shortened]

  def index
    @links = Link.order(clicked: :DESC)
  end

  def show
    update_link_attribute(@link)
    redirect_to @link.sanitize_url
  end

  def update_link_attribute(link)
    link.update_attribute(:clicked, link.clicked + 1)
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    @link.sanitize
    if @link.new_url?
      if @link.save
        redirect_to shortened_path(@link.short_url), notice: 'Link was successfully created.'
      else
        render :new
      end
    else
      flash[:notice] = 'A short link for this URL is already present in our database.'
      redirect_to shortened_path(@link.find_duplicate.short_url)
    end
  end

  def shortened
    @link = Link.find_by_short_url(params[:short_url])
    host = request.host_with_port
    @original_url = @link.sanitize_url
    @short_url = host + '/' + @link.short_url
  end

  def fetch_original_url
    fetch_url = Link.find_by_short_url(params[:short_url])
    redirect_to fetch_url.sanitize_url
  end

  def destroy
    return unless @link.destroy

    redirect_to links_url, notice: 'Link was successfully destroyed.'
  end

  private

  def find_link
    @link = Link.find_by_short_url(params[:short_url])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_link
    @link = Link.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def link_params
    params.require(:link).permit(:original_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortnerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if notice.present? %>
        <p id="notice" class="alert alert-primary mt-4"><%= notice %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>
      <ul>
        <% link.errors.full_messages.each do |message| %>
          <li class="alert alert-danger"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="row">
      <div class="col-md-12">
        <%= form.label :type_original_url %>
        <%= form.text_field :original_url, class: 'form-control' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 mt-2">
        <%= form.submit 'Create Link', class: 'btn btn-primary btn-block' %>
      </div>
    </div>
  </div>
<% end %>

app/views/links/index.html.erb
<h1>Links</h1>
<table class="table">
  <thead>
    <tr>
      <th>Original Url</th>
      <th>Short Url</th>
      <th>Total Clicked</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.original_url %></td>
        <td><%= link_to request.host + '/' + link.short_url, "/#{link.short_url}" %></td>
        <td><%= link.clicked %></td>
        <td><%= link_to 'Show', shortened_path(short_url: link.short_url), class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Link', new_link_path, class: 'btn btn-primary btn-sm' %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Go to All Links', links_path, class: 'btn btn-primary btn-sm' %>

app/views/links/shortened.html.erb
<div class="row">
  <div class="col-md-12">
    <h3>Link Details</h3>
    <hr>
  </div>
  <div class="col-md-6">
    <p>
      <strong>Original Url:</strong>
      <%= @link.original_url %>
    </p>
  </div>
  <div class="col-md-6">
    <p>
      <strong>Short Url:</strong>
      <%= link_to @short_url, "/#{@link.short_url}" %>
    </p>
  </div>
  <hr>
  <div class="col-md-12">
    <p>
      <strong>Total Clicks:</strong>
      <%= @link.clicked %> <%= @link.clicked > 1 ? 'times' : 'time' %>
    </p>
  </div>
</div>
<%= link_to 'Back', links_path, class: 'btn btn-info btn-sm' %>